<?php
$coala_slider_sc = coala_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $coala_slider_sc ) && strpos( $coala_slider_sc, '[' ) !== false && strpos( $coala_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( coala_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$coala_anchor_icon = coala_get_theme_option( 'front_page_title_anchor_icon' );
		$coala_anchor_text = coala_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $coala_anchor_icon ) || ! empty( $coala_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $coala_anchor_icon ) ? ' icon="' . esc_attr( $coala_anchor_icon ) . '"' : '' )
									. ( ! empty( $coala_anchor_text ) ? ' title="' . esc_attr( $coala_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $coala_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$coala_scheme = coala_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $coala_scheme ) && ! coala_is_inherit( $coala_scheme ) ) {
			echo ' scheme_' . esc_attr( $coala_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( coala_get_theme_option( 'front_page_title_paddings' ) );
		if ( coala_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$coala_css      = '';
		$coala_bg_image = coala_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $coala_bg_image ) ) {
			$coala_css .= 'background-image: url(' . esc_url( coala_get_attachment_url( $coala_bg_image ) ) . ');';
		}
		if ( ! empty( $coala_css ) ) {
			echo ' style="' . esc_attr( $coala_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$coala_anchor_icon = coala_get_theme_option( 'front_page_title_anchor_icon' );
		$coala_anchor_text = coala_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $coala_anchor_icon ) || ! empty( $coala_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $coala_anchor_icon ) ? ' icon="' . esc_attr( $coala_anchor_icon ) . '"' : '' )
									. ( ! empty( $coala_anchor_text ) ? ' title="' . esc_attr( $coala_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( coala_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' coala-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$coala_css      = '';
			$coala_bg_mask  = coala_get_theme_option( 'front_page_title_bg_mask' );
			$coala_bg_color_type = coala_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $coala_bg_color_type ) {
				$coala_bg_color = coala_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $coala_bg_color_type ) {
				$coala_bg_color = coala_get_scheme_color( 'bg_color', $coala_scheme );
			} else {
				$coala_bg_color = '';
			}
			if ( ! empty( $coala_bg_color ) && $coala_bg_mask > 0 ) {
				$coala_css .= 'background-color: ' . esc_attr(
					1 == $coala_bg_mask ? $coala_bg_color : coala_hex2rgba( $coala_bg_color, $coala_bg_mask )
				) . ';';
			}
			if ( ! empty( $coala_css ) ) {
				echo ' style="' . esc_attr( $coala_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$coala_caption = coala_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $coala_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $coala_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $coala_caption, 'coala_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$coala_description = coala_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $coala_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $coala_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $coala_description ), 'coala_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( coala_get_theme_option( 'front_page_title_button1_link' ) != '' || coala_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						coala_show_layout( coala_customizer_partial_refresh_front_page_title_button1_link() );
						coala_show_layout( coala_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
